# -*- coding: utf-8 -*-
"""translation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IwB06C2cTAnk7zJBq6C28kDH7G2HofxF
"""

pip install googletrans==3.1.0a0

from googletrans import Translator
translator = Translator()

out = translator.translate("क्या हाल है", dest='en')
print(out)

mystory = '''I am Rashi Pandey. This is my practice code.
'''

out = translator.translate(mystory, dest='hi')
print(out.text)

out = translator.translate("I am rashi I am learning Python", dest='gu')
print(out)